server:
  port: 3000 # 端口号
eureka:
  client:
    registerWithEureka: false # 是否注册到Eureka Server，单点的时候设置为false，禁止注册自身，集群为true
    fetchRegistry: false # 是否从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka # Eureka Client配置时使用的Eureka Server的地址
  server:
    enableSelfPreservation: false # 是否开启自我保护
    evictionIntervalTimerInMs: 4000 # 清理无效节点的时间间隔